const USERS=[
 {email:'empresa@demo.com',password:'demo123',role:'cazador',name:'NicaTech S.A.',photo:'img/profile-placeholder.svg'},
 {email:'natural@demo.com',password:'demo123',role:'natural',name:'María López',photo:'img/profile-placeholder.svg'},
 {email:'presa@demo.com',password:'demo123',role:'presa',name:'Carlos Mendoza',photo:'img/profile-placeholder.svg'},
 {email:'admin@demo.com',password:'demo123',role:'admin',name:'Administración',photo:'img/profile-placeholder.svg'}
];
const TALENTS=[
 {id:1,name:'Carlos Mendoza',profession:'Desarrollador web',experience:'5 años de experiencia',education:'Universitario',category:'Tecnología',location:'Managua',skills:['JavaScript','Diseño web','React'],photo:'img/profile-placeholder.svg',email:'carlos@example.com',phone:'+505 8888 1201',address:'Distrito I, Managua',schedule:'Remoto · Tiempo completo',document:'001-120295-0001A',birth:'1995-02-12',gender:'Masculino',medical:'Sin padecimientos reportados',motivation:'Quiero aportar soluciones digitales a equipos con impacto local.',recommendation:'Carta de recomendación adjunta.'},
 {id:2,name:'Ana Sofía Ruiz',profession:'Diseñadora gráfica',experience:'4 años de experiencia',education:'Técnico',category:'Diseño',location:'León',skills:['Branding','Illustrator','UX'],photo:'img/profile-placeholder.svg',email:'ana@example.com',phone:'+505 8777 3190',address:'Centro histórico, León',schedule:'Híbrido · Medio tiempo',document:'281-070798-0002B',birth:'1998-07-07',gender:'Femenino',medical:'Sin padecimientos reportados',motivation:'Busco crear identidades que conecten con las personas.',recommendation:'Dos cartas verificadas.'},
 {id:3,name:'José Martínez',profession:'Técnico electricista',experience:'8 años de experiencia',education:'Certificación técnica',category:'Servicios técnicos',location:'Masaya',skills:['Instalaciones','Mantenimiento','Industrial'],photo:'img/profile-placeholder.svg',email:'jose@example.com',phone:'+505 8666 5402',address:'Monimbó, Masaya',schedule:'Presencial · Por proyecto',document:'401-100190-0003C',birth:'1990-01-10',gender:'Masculino',medical:'Apto para trabajo físico',motivation:'Deseo conectar con clientes que valoren el trabajo seguro.',recommendation:'Carta de antiguo empleador adjunta.'},
 {id:4,name:'Lucía Hernández',profession:'Contadora pública',experience:'6 años de experiencia',education:'Universitario',category:'Administración',location:'Granada',skills:['Fiscalidad','Excel','Auditoría'],photo:'img/profile-placeholder.svg',email:'lucia@example.com',phone:'+505 8555 7421',address:'Calle La Calzada, Granada',schedule:'Remoto · Tiempo completo',document:'201-220393-0004D',birth:'1993-03-22',gender:'Femenino',medical:'Sin padecimientos reportados',motivation:'Quiero apoyar el crecimiento ordenado de nuevos negocios.',recommendation:'Tres referencias disponibles.'}
];
const app=document.querySelector('#app'); let selectedRole='cazador';
const db={get(k,f=[]){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
if(!localStorage.getItem('caza_users')) db.set('caza_users',USERS);
else db.set('caza_users',db.get('caza_users').map(user=>({...user,photo:user.photo?.includes('/profile/')?'img/profile-placeholder.svg':user.photo})));
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}
function log(action,detail,result='realizado'){const user=db.get('caza_session',{});const rows=db.get('caza_trace');rows.unshift({date:new Date().toLocaleString('es-NI'),user:user.name||'Visitante',role:user.role||'público',action,detail,result});db.set('caza_trace',rows)}
const logo=()=>`<div class="mini-brand"><img src="img/logo-caza-nica.svg" alt="Caza Nica"></div>`;
function landing(){
 db.set('caza_session',null);app.innerHTML=`<section class="landing"><div class="floaters"><span class="floater">?</span><span class="floater"><img src="img/profile-placeholder.svg" alt=""></span><span class="floater">?</span></div><header class="landing-head"><div class="brand"><img src="img/logo-caza-nica.svg" alt="Caza Nica"><span class="brand-tagline">DESCUBRÍ. EXPLORÁ. CONECTÁ.</span></div><img class="map-mark" src="img/mapa-nicaragua.svg" alt="Mapa de Nicaragua"></header><div class="landing-content"><h1 class="question">¿QUÉ SOS?</h1><p class="lead">Elegí tu perfil y comenzá a conectar oportunidades con el talento nicaragüense.</p><div class="role-grid">${roleCard('natural','◎','Cazador natural','Busco talento para un servicio personal.')}${roleCard('presa','♟','Presa · Talento','Quiero mostrar mis conocimientos y experiencia.')}${roleCard('cazador','▥','Empresa','Buscamos talento para nuestra organización.')}</div></div></section>`;
 document.querySelectorAll('[data-role]').forEach(x=>x.onclick=()=>auth(x.dataset.role));
}
function roleCard(role,icon,title,text){return `<button class="role-card" data-role="${role}"><span class="role-icon">${icon}</span><h2>${title}</h2><p>${text}</p><span class="arrow">Explorar →</span></button>`}
function auth(role,register=false){selectedRole=role;const label={cazador:'Empresa',natural:'Cazador natural',presa:'Presa · Talento'}[role];app.innerHTML=`<section class="auth-page"><aside class="auth-side green-texture">${logo()}<h1>${register?'CREÁ TU EXPEDIENTE':'HOLA, '+label.toUpperCase()}</h1><p>${register?'Completá la información para comenzar esta aventura. Tus datos permanecen en este dispositivo.':'Ingresá y encontrá la oportunidad que estás buscando.'}</p></aside><div class="auth-main"><div class="auth-box"><button class="back-link" id="home">← Elegir otro perfil</button><h2>${register?'Registro':'Iniciar sesión'}</h2><p>${label}</p><div class="tabs"><button class="${!register?'active':''}" id="loginTab">Ingresar</button><button class="${register?'active':''}" id="registerTab">Registrarme</button></div>${register?registerForm(role):loginForm()}</div></div></section>`;bindAuth(register)}
function loginForm(){return `<form id="loginForm"><div class="form-grid"><div class="field full"><label>Correo electrónico</label><input name="email" type="email" required placeholder="tu@correo.com"></div><div class="field full"><label>Contraseña</label><input name="password" type="password" required placeholder="••••••••"></div></div><div class="form-actions"><button class="btn" type="submit">Entrar a Caza Nica →</button></div><div class="demo">Demo: <b>${selectedRole==='cazador'?'empresa':selectedRole}@demo.com</b> · Contraseña: <b>demo123</b><br>Admin: <b>admin@demo.com</b> · <b>demo123</b></div></form>`}
function field(label,name,type='text',full=false,options=''){return `<div class="field ${full?'full':''}"><label>${label}</label>${options?`<select name="${name}" ${type==='required'?'required':''}>${options}</select>`:type==='textarea'?`<textarea name="${name}" required></textarea>`:`<input name="${name}" type="${type}" ${type!=='file'?'required':''}>`}${type==='file'?'<span class="file-note">La ruta se guarda localmente para esta propuesta.</span>':''}</div>`}
function registerForm(role){let fields=field('Correo','email','email')+field('Contraseña','password','password');if(role==='presa')fields+=field('Nombre completo','name')+field('Número de cédula','document')+field('Locación','location')+field('Domicilio','address')+field('Profesión','profession')+field('Nivel educativo / técnico','education','required',false,'<option>Primaria</option><option>Secundaria</option><option>Universitario</option><option>Certificación técnica</option>')+field('Carta de recomendación','recommendation','file')+field('Foto de perfil','photo','file')+field('Expectativa de trabajo','schedule','required',true,'<option>Remoto</option><option>Presencial</option><option>Híbrido</option><option>Horario nocturno</option><option>Por proyecto</option>')+field('Motivo de inscripción','motivation','textarea',true)+field('Condición física / médica (peso, altura, padecimientos)','medical','textarea',true)+field('Género','gender','required',false,'<option>Femenino</option><option>Masculino</option><option>No binario</option><option>Prefiero no indicar</option>')+field('Fecha de nacimiento','birth','date');else if(role==='cazador')fields+=field('Nombre de empresa','name')+field('Sector','sector','required',false,'<option>Tecnología</option><option>Comercio</option><option>Construcción</option><option>Salud</option><option>Educación</option><option>Turismo</option><option>Otro</option>')+field('Ubicación','location')+field('Domicilio','address', 'text',true)+field('Horario de atención','schedule')+field('Logo de empresa','photo','file');else fields+=field('Nombre y apellido','name')+field('Teléfono','phone','tel')+field('Departamento','department')+field('Ciudad','city')+field('Dirección específica','address','text',true)+field('Motivo de búsqueda','motivation','textarea',true)+field('Foto','photo','file');return `<form id="registerForm"><div class="form-grid">${fields}</div><div class="form-actions"><button class="btn" type="submit">Crear mi cuenta →</button></div></form>`}
function bindAuth(register){document.querySelector('#home').onclick=landing;document.querySelector('#loginTab').onclick=()=>auth(selectedRole,false);document.querySelector('#registerTab').onclick=()=>auth(selectedRole,true);const form=document.querySelector(register?'#registerForm':'#loginForm');form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));if(register){const users=db.get('caza_users');if(users.some(u=>u.email===data.email))return toast('Ese correo ya está registrado');data.role=selectedRole;data.photo='img/profile-placeholder.svg';users.push(data);db.set('caza_users',users);db.set('caza_session',data);log('Registro de cuenta',`Nuevo perfil ${selectedRole}`);dashboard()}else{const user=db.get('caza_users').find(u=>u.email===data.email&&u.password===data.password);if(!user)return toast('Correo o contraseña incorrectos');db.set('caza_session',user);log('Inicio de sesión','Acceso correcto');dashboard()}}}
function frame(content,sidebar=''){const u=db.get('caza_session',{});return `<section class="dashboard"><header class="topbar">${logo()}<div class="user-tools"><img class="avatar" src="${u.photo||'img/profile-placeholder.svg'}" alt="Perfil"><span>${u.name}</span><button class="logout" id="logout">Cerrar sesión</button></div></header><div class="dash-body">${sidebar}<main class="content">${content}</main></div></section>`}
function dashboard(){const u=db.get('caza_session');if(!u)return landing();if(u.role==='admin')return admin();if(u.role==='presa')return ownProfile();hunter()}
function bindLogout(){document.querySelector('#logout').onclick=()=>{log('Cierre de sesión','Sesión finalizada');landing()}}
function hunter(){const filters=`<aside class="sidebar"><h3>Filtrar talentos</h3>${filter('Categoría','category',['Todas','Tecnología','Diseño','Servicios técnicos','Administración'])}${filter('Nivel educativo','education',['Todos','Primaria','Secundaria','Universitario','Técnico','Certificación técnica'])}${filter('Experiencia','experience',['Cualquiera','1–3 años','4–6 años','7+ años'])}${filter('Conocimientos','skills',['Todos','JavaScript','Branding','Mantenimiento','Excel'])}${filter('Ubicación','location',['Toda Nicaragua','Managua','León','Masaya','Granada'])}<button class="btn" id="apply">Aplicar filtros</button></aside>`;renderTalents(TALENTS,filters)}
function filter(label,id,values){return `<div class="filter"><label>${label}</label><select id="${id}">${values.map(v=>`<option>${v}</option>`).join('')}</select></div>`}
function renderTalents(items,sidebar=document.querySelector('.sidebar')?.outerHTML||''){app.innerHTML=frame(`<div class="welcome"><div><h1>Encontrá tu próxima presa</h1><p>Talento listo para sumar valor a tu proyecto.</p></div><span class="count">${items.length} talentos</span></div><div class="talent-grid">${items.map(t=>`<article class="talent-card"><img src="${t.photo}" alt="Foto de ${t.name}"><h3>${t.name}</h3><p><b>${t.profession}</b><br>${t.experience} · ${t.location}</p><div class="chips">${t.skills.map(s=>`<span class="chip">${s}</span>`).join('')}</div><button class="btn view" data-id="${t.id}">Ver expediente →</button></article>`).join('')}</div>`,sidebar);bindLogout();document.querySelectorAll('.view').forEach(b=>b.onclick=()=>profile(+b.dataset.id));const apply=document.querySelector('#apply');if(apply)apply.onclick=()=>{let list=TALENTS;const cat=document.querySelector('#category').value,edu=document.querySelector('#education').value,loc=document.querySelector('#location').value,skill=document.querySelector('#skills').value;if(cat!=='Todas')list=list.filter(x=>x.category===cat);if(!['Todos'].includes(edu))list=list.filter(x=>x.education===edu);if(loc!=='Toda Nicaragua')list=list.filter(x=>x.location===loc);if(skill!=='Todos')list=list.filter(x=>x.skills.includes(skill));log('Aplicación de filtros',`${cat}, ${edu}, ${loc}`);renderTalents(list,document.querySelector('.sidebar').outerHTML)}}
function age(date){const d=new Date(date),n=new Date();let a=n.getFullYear()-d.getFullYear();if(n<new Date(n.getFullYear(),d.getMonth(),d.getDate()))a--;return a}
function info(label,value){return `<div class="datum"><small>${label}</small><strong>${value}</strong></div>`}
function profile(id){const t=TALENTS.find(x=>x.id===id);log('Consulta de perfil',t.name);app.innerHTML=frame(`<div class="profile-sheet"><button class="back-link" id="back">← Resultados</button><section class="profile-hero"><img src="${t.photo}" alt="Foto de ${t.name}"><div><span class="chip">PRESA VERIFICADA</span><h1>${t.name}</h1><p>${t.profession} · ${t.location}</p></div></section><div class="profile-sections"><section class="info-card"><h3>Identidad profesional</h3><div class="data-list">${info('Experiencia',t.experience)}${info('Educación',t.education)}${info('Cédula',t.document)}${info('Género',t.gender)}${info('Edad',age(t.birth)+' años')}${info('Fecha de nacimiento',t.birth)}</div></section><section class="info-card"><h3>Disponibilidad y bienestar</h3><div class="data-list">${info('Modalidad',t.schedule)}${info('Condición reportada',t.medical)}</div></section><section class="info-card full"><h3>Acerca de este talento</h3><p>${t.motivation}</p><div class="chips">${t.skills.map(s=>`<span class="chip">${s}</span>`).join('')}</div></section><section class="info-card full"><h3>Recomendaciones</h3><p>📎 ${t.recommendation}</p></section></div><div class="contact-lock"><h3>¿Te interesa este talento?</h3><p>Los datos de contacto están protegidos.</p><button class="btn btn-red" id="contact">Ver datos de contacto</button></div></div>`);bindLogout();document.querySelector('#back').onclick=hunter;document.querySelector('#contact').onclick=()=>contactModal(t)}
function contactModal(t){document.body.insertAdjacentHTML('beforeend',`<div class="modal-wrap" id="modal"><div class="modal"><h2>Datos protegidos</h2><p>A continuación se mostrarán los datos de contacto de esta presa. Asegurá que sos una empresa o persona real y que usarás estos datos con fines adecuados.</p><div class="form-actions"><button class="btn btn-light" id="deny">No aceptar</button><button class="btn" id="accept">Aceptar y ver</button></div></div></div>`);document.querySelector('#deny').onclick=()=>{log('Intento de contacto',`Presa: ${t.name}`,'no aceptó');document.querySelector('#modal').remove();toast('No se mostraron los datos')};document.querySelector('#accept').onclick=()=>{log('Acceso a contacto',`Presa: ${t.name}`,'aceptó');document.querySelector('.modal').innerHTML=`<h2>Contacto de ${t.name}</h2><div class="data-list">${info('Correo',t.email)}${info('Teléfono',t.phone)}${info('Domicilio',t.address)}</div><div class="form-actions"><button class="btn" id="close">Listo</button></div>`;document.querySelector('#close').onclick=()=>document.querySelector('#modal').remove()}}
function ownProfile(){const u=db.get('caza_session');const t={...TALENTS[0],...u,name:u.name||TALENTS[0].name};app.innerHTML=frame(`<div class="profile-sheet"><div class="welcome"><div><h1>Mi expediente de talento</h1><p>Así te encuentran los cazadores.</p></div><button class="btn">Editar perfil</button></div><section class="profile-hero"><img src="${t.photo}" alt="Foto de perfil"><div><span class="chip">PERFIL ACTIVO</span><h1>${t.name}</h1><p>${t.profession||'Profesional'} · ${t.location||'Nicaragua'}</p></div></section><div class="profile-sections"><section class="info-card"><h3>Datos profesionales</h3><div class="data-list">${info('Profesión',t.profession||'Por completar')}${info('Educación',t.education||'Por completar')}${info('Cédula',t.document||'Por completar')}${info('Edad',t.birth?age(t.birth)+' años':'Por completar')}</div></section><section class="info-card"><h3>Preferencias</h3><div class="data-list">${info('Expectativa',t.schedule||'Por completar')}${info('Género',t.gender||'Por completar')}</div></section><section class="info-card full"><h3>Motivo de inscripción</h3><p>${t.motivation||'Aún no agregaste esta información.'}</p></section><section class="info-card full"><h3>Documentos y recomendaciones</h3><p>📎 ${t.recommendation||'Sin cartas adjuntas'}</p></section></div></div>`);bindLogout()}
function admin(){const rows=db.get('caza_trace');app.innerHTML=frame(`<div class="welcome"><div><h1>Trazabilidad</h1><p>Actividad registrada localmente en la plataforma.</p></div><span class="count">${rows.length} eventos</span></div><div style="overflow:auto"><table class="admin-table"><thead><tr><th>Fecha y hora</th><th>Usuario / rol</th><th>Acción</th><th>Detalle</th><th>Resultado</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.date}</td><td><b>${r.user}</b><br>${r.role}</td><td>${r.action}</td><td>${r.detail}</td><td><span class="status ${r.result==='aceptó'?'yes':r.result==='no aceptó'?'no':''}">${r.result}</span></td></tr>`).join('')||'<tr><td colspan="5">Aún no hay actividad.</td></tr>'}</tbody></table></div>`);bindLogout()}
landing();
